### ISSUE TITLE
Technology Research of SignalR.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/SampleProgram#4]
# Requirement
- Technology Research of signalR, clarification of the function. 
  - Verification by the sample code about each function.

- Also, I want to create a sample of the following from the survey results.
  - Chat application that runs on AzureWeb site 
  - Request a translation function using the "Google Translate API".
  - We will create specification.

**Comment by kishoreandukuri** [comment]
HODC has started technology research on signal R.
We have done research on the following as per Nishino-san’s specifications in GitHub
•	What is SignalR
•	Features or functionalities of SignalR
•	Important techniques of SignalR
•	Models of SignalR
•	How to create sample application of Signal R using Visual Studio

HODC has also created sample program of chat application using signal R.

Currently,  we are creating research document for the functionalities of signal R with the help of chat application.

Please confirm, are these sufficient to complete the research?

Please let us know if the research needs to be done on more concepts of signal R.

>>Request a translation function using the "Google Translate API".
>>We will create specification.

HODC is requesting Nishino-san to share the specifications of Google translate application.

Thanks and Regards,

**Comment by daisukenishino2** [comment]
#A1
I think it's enough. However, if there is a shortage on the contents of the research document, I will request an additional research.

#A2
There is information on the Internet.

- 翻訳のWebAPI「Google Translate API」の使い方 - 強火で進め  
http://d.hatena.ne.jp/nakamura001/20110320/1300628805
- Translate API Getting Started - Google Translate API — Google Cloud Platform  
https://cloud.google.com/translate/v2/getting_started
- Using REST - Google Translate API — Google Cloud Platform  
Identifying your application to Google  
https://cloud.google.com/translate/v2/using_rest#auth

I generated the key to select the Server key in the Public API access in Google Developers Console.
and, "Accept requests from the following server IP address." input field was entered the IP address that obtained in the following.

-　アクセス情報【使用中のIPアドレス確認】  
[IP address confirmation in use] access information  
https://www.cman.jp/network/support/go_access.cgi

# I tried to run.
But the following error is returned.
Oh dear! Google Translate API's seems a paid service.

https://www.googleapis.com/language/translate/v2?key=[INSERT-YOUR-KEY]&target=ja&q=Hello
```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "ipRefererBlocked",
    "message": "There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed.",
    "extendedHelp": "https://console.developers.google.com"
   }
  ],
  "code": 403,
  "message": "There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed."
 }
}
```

**Comment by daisukenishino2** [comment]
# Microsoft Translator API
I found another translation API (Microsoft Translator API).
I will consider whether to use either of the two API.
- Google Translate API.
- Microsoft Translator API.
  - Microsoft Translator API プログラミング解説  
http://so-zou.jp/web-app/tech/web-api/bing/translator/
     - GetAppIdToken Method  
https://msdn.microsoft.com/en-us/library/ff512398.aspx
     - Translate Method  
https://msdn.microsoft.com/en-us/library/ff512406.aspx

**Comment by daisukenishino** [comment]
# Deliverable
Please commit the sample which was developed in this technology research.
https://github.com/OpenTouryoProject/SampleProgram/tree/master/ASPNET/SignalR/SignalRChat

- Do not commit technology research document at the here.
- Please fill in explanetaion of the procedure to execute about committed project/solution to [README.md](https://github.com/OpenTouryoProject/SampleProgram/blob/master/ASPNET/SignalR/SignalRChat/README.md).

**Comment by daisukenishino** [comment]
# Additional requests
Please research how to scaleout SignalR using the Radis.

- SignalR Scaleout with Redis  The ASP.NET Site  
http://www.asp.net/signalr/overview/performance/scaleout-with-redis

**Comment by kishoreandukuri** [comment]
Can HODC take this task into next sprint?

Please let us know.

**Comment by daisukenishino** [comment]
Yes, you can.
Please make out a schedule for these tasks at the subsequent sprint.

**Comment by daisukenishino** [comment]
I have made changes to the "OpenTouryoProject/SampleProgram" repository.
Therefore, please pull this changes of this repository from local repository of Symphony Teleca.

**Comment by daisukenishino** [comment]
Take corrective corresponding to point out to the research documents before embarking on the development of the chat application.

**Comment by supragyan** [comment]
Dear Nishino-San,

HODC wants to confirm:
\>\>But the following error is returned.
\>\>Oh dear! Google Translate API's seems a paid service.

To check the above error 
1.we need to create one sample Translation application by using Google Translate API.
To achieve this we  will follow 'https://cloud.google.com/translate/v2/getting_started'
2.Then need to invoke Google Translate API in that sample Translation application.
  How to invoke API :
   a.Google Translate API can be invoked by REST API URI.
   b.Or can be invoked by  using  REST from JavaScript using callback query parameter and a        callback function.
HODC wants to confirm which one we will follow for invoking API?
3.Then HODC will check the same error 'Oh dear! Google Translate API's seems a paid service.'  is showing or not?
4.HODC did check its showing Google Translator API and Microsoft Translator API are paid service only.
Our understanding is correct or not Please confirm

**Comment by supragyan** [comment]
Dear Nishino-San,
\>\>I generated the key at Public API access section in the Google Developers Console.
\>\>push "create new key" button.
\>\>select the server key.
HODC did check this by creating Server key and browser key.
When created browser key following error showing.
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceeded",
    "message": "Daily Limit Exceeded"
   }
  ],
  "code": 403,
  "message": "Daily Limit Exceeded"
 }
}
And when created server key following error showing.
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "ipRefererBlocked",
    "message": "There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed.",
    "extendedHelp": "https://console.developers.google.com"
   }
  ],
  "code": 403,
  "message": "There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed."
 }
\>\>Oh dear! Google Translate API's seems a paid service.
Yes Google Translator seems as paid service.

Now HODC checking for Microsoft Translator.

Is this ok or not please confirm.

**Comment by supragyan** [comment]
Dear Nishino-San,
\>\>there is a need to consider that we should call the API from anywhere.

\>\>from the client side?
\>\>Or from the server side?
\>\>To use of referer is said dangerous. 
\>\>Therefore, "from the server-side." should be selected.
Here "client side" means we need to call translate API through "javascript"
and server side means we need to call translate API through "code behind"

HODC understanding is correct or not please confirm.

**Comment by daisukenishino** [comment]
# Change
Development projects have been moved to the following repository.

Internationalized SignalR chat tool · Issue #7 · OpenTouryoProject-CloudOS
https://github.com/OpenTouryoProject/CloudOS/issues/7

Please register only sample of SignalR and Microsoft Translator API at here.

**Comment by supragyan** [comment]
Dear Nishino-San,
HODC did created specification of Chat application using automatic translation.
Do we need to upload in below location:
'https://github.com/SymphonyTeleca/CloudOS/tree/master/documents/SignalRChatTool/

Please confirm.
