### ISSUE TITLE
We will accept your proposal for UI improvement of SPA.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/SampleProgram#5]
# Requirement
Certainly we are unhappy with the design of the current screen. 
If possible, we request the improvement of the design.

However,
if the code is difficult to understand for the design improvements,
it is putting the cart before the horse. For example, such as the following.
- MVVM design of knockout JS 
  - Data binding 
  - Command binding 
- Implementation of call part of the ASP.NET Web API

Please add SPA_WebAPI_EF sample to the following location in the beginning.
https://github.com/OpenTouryoProject/SampleProgram/tree/master/Template/SPA_WebAPI_EF

After that, please perform the UI improvement of SPA for the added sample.
I will review the change of UI improved using a "pull request".

**Comment by SandeepNayak077** [comment]
HODC undrestood above comments as follows:
     •	First, HODC need to copy 'SPA_Sample' project
        From the following location https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2012/programs/C%23/Samples/WebApp_sample
        To the following location
https://github.com/OpenTouryoProject/SampleProgram/tree/master/Template/SPA_WebAPI_EF
   
   •	After completion of copy process, modify the UI design of ‘SPA_Sample' project for good Look-and-Feel (UI improvements) of the sample screens

Please confirm our understandings.

**Comment by daisukenishino** [comment]
Previously, solution set that was developed by ritu-san was present.
However, now it can not be confirmed on both of Github and IPServer.
Please check the status of the takeover of this work to Sai-san.

I place below a solution set (SPA_WebAPI_EF.zip) that I have owned.
[/V-RO/PJ2]
But, there is possibility that it is potentially stale.

**Comment by SandeepNayak077** [comment]
Thank you Nishino-san for your valuable comments.

HODC will get the status of this work with Sai-san
HODC will compare the solution set given by you and latest solution available with Sai-san and check for the stable solution of 'SPA_WebAPI_EF'

**Comment by SandeepNayak077** [comment]
HODC temporarily to put on hold of this task.
Because HODC wants to have more uderstanding on the concept of AsyncProcessingService and CopyTool website.
HODC wants to do better development in the AsyncProcessingService and CopyTool website, since it has high priority.
After completion of complete development of AsyncProcessingService and CopyTool website, HODC will immediately continue working on 'SPA_WebAPI_EF' application.

Please comfirm and let us know

**Comment by daisukenishino** [comment]
Roger that.
