### ISSUE TITLE
Research to support claims-based authentication of ID-Federation by WIF

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/SampleProgram#7]
# Requirement
To support ID-Federation with WIF(Windows Identity Foundation) in OpenTouryo, please add the sample code [here](https://github.com/OpenTouryoProject/SampleProgram/tree/master/ASPNET/ID-Federation).

- This sample is "preliminary investigation" "to support".
- This sample does not need to use the OpenToutryo.

## About support configurations
This program is required that it support two configurations:

- [Single IdP configuration : ASP.NET WebSite is connecting by federation trust relationship with ADFS or AZAD](http://www.agileit.com/single-sign-on-sso-for-office-365-and-other-cloud-services/).  
  - ASP.NET WebSite - ( connecting by FTR ) - ADFS(ADDS)
  - ASP.NET WebSite - ( connecting by FTR ) - AZAD

- Hybrid IdP configuration : WebSite is connecting by federation trust relationship with ADFS over AZAD or ADFS Proxy. e.g. : [Diagram 1](http://blogs.technet.com/cfs-file.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-00-56-58-metablogapi/2234.image_5F00_8.png), [Diagram 2](http://www.slideshare.net/kthrtty/101102-ms-techfielderidaasandazurefinal/35).
  - ASP.NET WebSite - ( connecting by FTR ) - AZAD or ADFS Proxy - ( connecting by FTR ) - ADFS(ADDS)

## About implementation
However, the two configurations have the difference about only infrastructure.
Therefor,  there is a possibility that maybe there is no need to change the application.

First, you must realize the claims-based authentication in the Single IdP configuration environment.

# Terminology
- WIF : Windows Identity Foundation
- ADDS : Active Directory Domain Services
- ADFS : Active Directory Federation Services 
- AZAD : Azure Active Directory
- IdP : Identity Provider ( = ADDS )
  - CP : Claim Provider( = Idp at WS-Federation model)
- STS : Security Token Service ( = ADFS or AZAD )
- SP : Service Provider( = ASP.NET WebSite)
  - RP : Relying Party( = SP at WS-Federation model)
- FTR : Federation Trust Relationship

- In the case of Hybrid structure, STS is classified into two types.
  - SP side STS : AZAD or ADFS Proxy
  - IDP side STS : ADFS

Service Providers, Identity Providers & Security Token Services
http://www.empowerid.com/learningcenter/technologies/service-identity-providers

**Comment by daisukenishino** [comment]
# Information gathering
- Identity Delegation with AD FS 2.0 Step-by-Step Guide  
https://technet.microsoft.com/en-us/library/adfs2-identity-delegation-step-by-step-guide.aspx
- AD FS 2.0 Federation with a Windows Identity Foundation (WIF) Application Step-by-Step Guide  
https://technet.microsoft.com/en-us/library/adfs2-federation-wif-application-step-by-step-guide.aspx

-  To claims-based authentication by connecting a trust relationship with ADFS.  
ADFS 2.0 with a WIF Application Step-by-Step してみたよ  ブチザッキ  
https://buchizo.wordpress.com/2010/06/23/adfs-2-0-with-a-wif-application-step-by-step-%E3%81%97%E3%81%A6%E3%81%BF%E3%81%9F%E3%82%88/

- WIF and WAAD(AzureAD)
  - Macaw - Authentication in ASP.NET MVC with WIF and WAAD  
https://www.macaw.nl/weblog/2013/9/authentication-in-asp-net-mvc-with-wif-and-waad
  - How to use Access Control (.NET) - Azure feature guide  
http://azure.microsoft.com/en-us/documentation/articles/active-directory-dotnet-how-to-use-access-control/

**Comment by daisukenishino** [comment]
# To-Do
## (1) First
Build a system with a simple configuration of the following,
- ASP.NET WebSite - (connecting by FTR) - ADFS(ADDS)
Next, please create a sample to perform claims-based authentication.

## (2) Second
Build a system with a hybrid IDP configuration using the following AzureAD and ADFS.
- ASP.NET WebSite - (connecting by FTR) - Azure AD - (connecting by FTR) - ADFS
You verify the operation of the sample application that was developed in the above.

**Comment by daisukenishino** [comment]
# Sequence of authentication process by the WS- Federation
WS-Federation - マイクロソフト系技術情報 Wiki > 処理シーケンス > SAMLトークンのパッシブ モード
WS-Federation - Microsoft-based technical information Wiki > processing sequence > Passive mode of SAML token
http://techinfoofmicrosofttech.osscons.jp/index.php?WS-Federation#j4a8d6c6

- "ADDS" as "IdP"  
  (6). ↑: authentication request  
  (7). ↓: authentication completion
- "ADFS as "STS"
  (3). ↑: (continuation of the No.4) redirect to the STS and is ADFS.
  (4). ↓: Send a logon page to the client
  (5). ↑: send by entering the user account information
  (8). ↓: to issue a SAML token
- client (WWW browser)
  (1). ↓: anonymous requests
  (2). ↑: HTTP302, redirection to ADFS.
  (9). ↓: access by using the token.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have updated the SingleIDP document and uploaded in the server.
Due to some technical issue I could not send mail.
So, we will send mail about the delivery of document by tomorrow.

File location in the server: <b>/Delivery/20160114/</b>

After sending mail, I will delete this comment.
Sorry for the inconvenience.

**Comment by daisukenishino** [comment]
@SandeepNayak077

I deleted the above comment, because I have confirmed the delivery.

**Comment by daisukenishino** [comment]
@SandeepNayak077 
@supragyan 

> https://github.com/OpenTouryoProject/SampleProgram/issues/7#issue-78489895
please add the sample code [here](https://github.com/OpenTouryoProject/SampleProgram/tree/master/ASPNET/ID-Federation).

When will it be delivered this sample ?

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> When will it be delivered this sample ?

This sample will be delivered by today EOD.

<h3>About the sample website<h3>

Since both singly and hybrid IDP sample website applications have same implementation,
We will commit only 1 sample website application with solution name as ClaimsWeb_sample.sln.

We will update the sample website(/ID-Federation/ClaimsWeb_sample/) that does not contain the configuration of FedUtil tool in web.config file.

Please confirm our understanding.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>We will update the sample website(/ID-Federation/ClaimsWeb_sample/) that does not contain the configuration of FedUtil tool in web.config file.

Please ship the following two web.config to the pullrequest.
- Not including the setting of FedUtil : web.config
- Including the setting of FedUtil : web.config_

**Comment by SandeepNayak077** [comment]
@daisukenishino 

>Please ship the following two web.config to the pullrequest.

Sure, we will update as described above.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Currently, the [web.config_](https://github.com/OpenTouryoProject/SampleProgram/issues/7#issuecomment-173164210) file is not added to the ClaimsWeb_sample.csproj, but file exits on the location.

Is that file required to included in the project?

please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

There is no need to include web.config_ to ClaimsWeb_sample.csproj.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for confirmation.
We have created [pull request-12](https://github.com/SymphonyTeleca/SampleProgram/pull/12).

please review and let us know.
